### ISSUE TITLE
skill_check

### ISSUE THREAD

**Issue by miron** [miron/NeonCore#52]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/NeonCore/NeonCore/__main__.py", line 10, in <module>
    act_mngr.start_game()
  File "/root/NeonCore/NeonCore/managers/action_manager.py", line 38, in start_game
    self.cmdloop()
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/root/NeonCore/NeonCore/game_mechanics/skill_check.py", line 90, in do_use_skill
    if skill_name not in self.character.get_skills():
AttributeError: 'ActionManager' object has no attribute 'character'
```

**Comment by miron** [comment]
self.char_mngr.player is perfectly fine in do_* methods.
